graph TD
    Glc[Glucose] --> G6P[Glucose-6-Phosphate]
    G6P --> F6P[Fructose-6-Phosphate]
    F6P --> F16BP[Fructose-1,6-Bisphosphate]
    F16BP --> DHAP[Dihydroxyacetone Phosphate]
    F16BP --> G3P[Glyceraldehyde-3-Phosphate]
    G3P --> BPG[1,3-Bisphosphoglycerate]
    BPG --> 3PG[3-Phosphoglycerate]
    3PG --> 2PG[2-Phosphoglycerate]
    2PG --> PEP[Phosphoenolpyruvate]
    PEP --> Pyr[Pyruvate]
